/********
 * This file is the runtime for the language
 * It is linked to the file after the assembly is generated by my compiler.
 *******/
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
bool putinteger(int a) {
  printf("%i\n", a);
  return true;
}

int getinteger() {
  int ret;
  scanf("%i", &ret);
  return ret;
}

bool getbool() {
  int ret;
  scanf("%i", &ret);
  return (ret == 1);
}

bool putbool(bool in) {
  printf("%i", in);
  return true;
}

float getfloat() {
  float ret;
  scanf("%f", &ret);
  return ret;
}

bool putfloat(float in) {
  printf("%f", in);
  return true;
}

char* getstring() {
  char string[256];
  scanf("%s", string);
  return string;
}

bool putstring(char *string) {
  printf("%s\n", string);
  return true;
}

float mysqrt(int in) {
  return sqrt((double)in);
}
